### ISSUE TITLE
checkpoints Not Found

### ISSUE THREAD

**Issue by Lightingning** [rotemtzaban/STIT#15]
When executing latter commands,the program reports an error: FileNotFoundError: [Errno 2] No such file or directory: './checkpoints/model_jim.pt'
And I checked out the project on Github, and found that in the directory STIT, there isn't a directory named checkpoints.
Have this directory been removed from the project?

**Comment by rmokady** [comment]
To obtain the checkpoint, you first need to tune the model as instructed

Since it is a quite quick procedure we do not provide checkpoints

**Comment by 2min77** [comment]
Sir, if the same function is to be realized on different people's faces, do we need to retrain checkpoint every time?The Obama checkpoint I trained doesn't seem to work for anyone else.
