### ISSUE TITLE
How to use the pre-trained StyleGAN2 for another architecture?

### ISSUE THREAD

**Issue by mazzzystar** [rotemtzaban/STIT#19]
Hi I want to replace the pre-trained StyleGAN2 model `ffhq.pkl` with [rosinality's StyleGAN2 Implementation](https://github.com/rosinality/stylegan2-pytorch), It seems that currently your implementation of StyleGAN2 is based on [StyleGAN2-ada](https://github.com/NVlabs/stylegan2-ada-pytorch). These two implementations have different weights paramenters & architecture.  Besides changing the Generator network, Is there any  way for a convertion?  Thanks  for your great work!

**Comment by rotemtzaban** [comment]
@mazzzystar 
Hi,
Unfortunately I don't think there is a simple way to do this other than changing all the generator references to use rosinality's implementation.
Perhaps you could alternatively write a script similar to this one: https://github.com/rosinality/stylegan2-pytorch/blob/master/convert_weight.py, that would perform the conversion for the weights file.

**Comment by mazzzystar** [comment]
Many thanks!
