### ISSUE TITLE
missing import line in styleclip_global_utils.py?

### ISSUE THREAD

**Issue by bycloudai** [rotemtzaban/STIT#20]
Hi, thank you so much for sharing this amazing work.
I just wanted to ask that if there's a missing line `import clip` in the file `editings/styleclip_global_utils.py`, because I got the following error when trying to run it with styleclip and it was fixed by adding that import line.

![image](https://user-images.githubusercontent.com/29135514/157763822-d7888357-7bc7-4a36-b5dd-e270c527f14a.png)

Thanks!

**Comment by a-ggghost** [comment]
Same here. I thought it was strange because the line seems deliberately removed in a3389eb04067837e82d61e99bdb2f5c072a81272

**Comment by rotemtzaban** [comment]
Hi,
I accidentally removed this line earlier but it has already been fixed. Are you working with the latest version?
The current implementation imports clip in a try... excpet block, to allow users to use the regular edits without installing clip.
