### ISSUE TITLE
edit_video_stitching_tuning.py has a dependency on "FreeSans" font being installed

### ISSUE THREAD

**Issue by sam598** [rotemtzaban/STIT#6]
Changing line

`font = ImageFont.truetype("truetype/freefont/FreeSans.ttf", font_size)`

to

`font = ImageFont.load_default()`

is a quick fix.

**Comment by johndpope** [comment]
https://zoomadmin.com/HowToInstall/UbuntuPackage/fonts-freefont-otf - maybe helpful

**Comment by rotemtzaban** [comment]
Thanks for raising that problem(and also proposing a solution).
I'll update the code to use the default font as backup.

**Comment by rotemtzaban** [comment]
@sam598 
I added the default font as fallback, please update if there are any more issues with that
