### ISSUE TITLE
ValueError: Image must be a numpy array.

### ISSUE THREAD

**Issue by onefish51** [rotemtzaban/STIT#7]
```sh
File "edit_video.py", line 137, in _main
    imageio.mimwrite(os.path.join(folder_path, 'out.mp4'), frames, fps=18, output_params=['-vf', 'fps=25'])
  File "/opt/conda/lib/python3.8/site-packages/imageio/core/functions.py", line 338, in mimwrite
    raise ValueError('Image must be a numpy array.')
```

>imageio.mimwrite(uri, ims, format=None, **kwargs)
Write multiple images to the specified file.
Parameters
...
ims [sequence of numpy arrays] The image data. Each array must be NxM, NxMx3 or NxMx4.

So there is something wrong.

**Comment by johndpope** [comment]
what happens if you print frames ? it seems like something is going wrong upstream...

**Comment by onefish51** [comment]
from `add_texts_to_image_vertical` and `video_frames[folder_name].append(video_frame)`, it's `list(PIL.Image.Image)`

**Comment by rotemtzaban** [comment]
@onefish51 
I would guess that both issues are version issues, can you try to upgrade imageio and imageio-ffmpeg.
The versions that I use are:
imageio==2.16.0
imageio-ffmpeg==0.4.5

**Comment by rotemtzaban** [comment]
As for the numpy array/PIL image, I will test if it works well with numpy arrays and update it.

**Comment by onefish51** [comment]
Successfully installed imageio-2.16.0
